# Generated by Django 2.1.2 on 2018-10-08 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seat_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seat',
            old_name='is_dissabled',
            new_name='is_disabled',
        ),
    ]
